[package]

name = "capnp-rpc"
version = "0.10.0-dev"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"
categories = ["network-programming"]
autoexamples = false

readme = "README.md"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = { version = "0.10.0-dev", path = "../capnpc" }

[dependencies]
futures = "0.1.15"
capnp-futures = { version = "0.10.0-dev", path = "../capnp-futures" }
capnp = {version = "0.10.0-dev", path = "../capnp",  features = ["rpc"]}
