[package]

name = "capnp-rpc"
version = "0.12.3"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/capnproto/capnproto-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"
categories = ["network-programming"]
autoexamples = false
edition = "2018"

readme = "README.md"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[dependencies]
futures = "0.3.0"
capnp-futures = { version = "0.12.0", path = "../capnp-futures" }
capnp = {version = "0.12.2", path = "../capnp"}
