[package]

name = "capnp-rpc"
version = "0.8.2"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"
categories = ["network-programming"]

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.8.8"

[dependencies]
futures = "0.1.15"
capnp-futures = "0.1"
capnp = {version = "0.8.13", features = ["rpc"]}

[[example]]
# prevent 'cargo test' from trying to build the examples
name = "dummy"
path = "examples/dummy.rs"
