[package]

name = "capnpc"
version = "0.10.0-dev"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
license = "MIT"
description = "Cap'n Proto code generation"
repository = "https://github.com/capnproto/capnproto-rust"
documentation = "http://docs.capnproto-rust.org/capnpc"
edition = "2018"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]

[lib]

name = "capnpc"
path = "src/lib.rs"

[[bin]]

name = "capnpc-rust"
path = "src/capnpc-rust.rs"

[[bin]]

name = "capnpc-rust2018"
path = "src/capnpc-rust2018.rs"

[dependencies]
capnp = { version = "0.10.0-dev", path = "../capnp" }

