[package]

name = "addressbook_send"
version = "0.0.0"
authors = ["David Renshaw <dwrenshaw@gmail.com>"]
edition.workspace = true
license.workspace = true

[[bin]]

name = "addressbook_send"
path = "addressbook_send.rs"

[dependencies]
capstone.workspace = true
capstone-import.workspace = true
