[package]

name = "addressbook_send"
version = "0.0.0"
authors = ["David Renshaw <dwrenshaw@gmail.com>"]
edition = "2021"

[[bin]]

name = "addressbook_send"
path = "addressbook_send.rs"

[dependencies]
capnp = { path = "../../capnp" }
capnp-import = { path = "../../capnp-import" }
