dist: trusty
sudo: false
language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.16.0
      script: # OK if RPC feature uses newer rustc features
        - cargo test -p capnp
        - cargo test -p capnpc
env:
  global:
    - export PATH="$PATH:$HOME/bin"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"
addons:
  apt:
    packages:
      - gcc
      - g++
install:
  - curl -O https://capnproto.org/capnproto-c++-0.5.3.tar.gz
  - tar zxf capnproto-c++-0.5.3.tar.gz
  - cd capnproto-c++-0.5.3
  - ./configure --prefix=$HOME
  - make -j3
  - make install
  - cd ../

script:
  - cargo build
  - cargo test
  - cargo clean
  - cargo build --all
  - cargo test --all
  - ./target/debug/addressbook write | ./target/debug/addressbook read
  - cargo clean
  - cargo build --all --release
  - ./target/release/run_all_benchmarks target/release/benchmark
  - cargo test --all --release

