sudo: false
language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.16.0
      script: cargo test # OK if RPC feature uses newer rustc features
script:
  - cargo build
  - cargo test
  - cargo doc
  - cargo clean
  - cargo build --features rpc
  - cargo test --features rpc
  - cargo doc --features rpc
