@0xc27a1f1d49c5e0be;

$import "/capnp/c++.capnp".namespace("capnp");

interface Introspect @0xb630c9d241dcd873 {
  # Optional universal introspection interface that can be generated by
  # a codegen backend, if desired. 

  introspect @0 () -> (schemas :List(UInt64));
  # Returns the brand ID of all interfaces implemented by this cap (except this one)
}