[package]

name = "shared-secret-capability"
version = "0.0.0"
authors = ["Adam Schwab <aschwab@cloudflare.com>"]
edition = "2021"

build = "build.rs"

[[bin]]
name = "shared-secret-capability"
path = "main.rs"

[build-dependencies]
capstone-gen.workspace = true

[dependencies]
capstone.workspace = true
capstone-rpc.workspace = true
tokio = { version = "1.0.0", features = ["net", "rt", "macros"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
futures-util.workspace = true

[lints]
workspace = true
