[package]
name = "capnp-futures"
version = "0.1.1"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"

description = "async serialization for Cap'n Proto messages"
repository = "https://github.com/dwrensha/capnp-futures-rs"
documentation = "https://docs.capnproto-rust.org/capnp_futures/"

keywords = ["async"]

[dependencies]

byteorder = "1.0"
capnp = "0.8"
futures = "0.1.12"

[dev-dependencies]
capnp = { version = "0.8", features = ["quickcheck"] }
quickcheck = "0.2"
