[package]
name = "capnp-futures"
version.workspace = true
authors = ["David Renshaw <drenshaw@gmail.com>"]
license.workspace = true
description = "async serialization for Cap'n Proto messages"
repository.workspace = true
documentation = "https://docs.rs/capnp-futures/"
edition.workspace = true
readme = "README.md"

keywords = ["async"]

[dependencies]
capnp.workspace = true
quickcheck = { version = "1", optional = true }
futures.workspace = true

[dev-dependencies]
capnp = { workspace = true, features = ["quickcheck"] }
futures = { workspace = true, features = ["executor"] }
quickcheck = "1"
