[package]

name = "capnp-rpc-test"
version = "0.0.0"
authors = ["David Renshaw <dwrenshaw@sandstorm.io>"]
edition.workspace = true
license.workspace = true

[lib]

name = "capnp_rpc_test"
path = "test.rs"

[dev-dependencies]
async-byte-channel.workspace = true
capstone-rpc.workspace = true
futures-util.workspace = true
capstone.workspace = true
tokio.workspace = true

[build-dependencies]
capstone-gen.workspace = true

[lints]
workspace = true
