[package]

name = "addressbook"
version = "0.0.0"
authors = ["David Renshaw <dwrenshaw@gmail.com>"]
edition = "2018"

[[bin]]

name = "addressbook"
path = "addressbook.rs"

[dependencies.capnp]
path = "../../capnp"
capnp-import = { path = "../../capnp-import" }
