[package]

name = "addressbook"
version = "0.0.0"
authors = ["David Renshaw <dwrenshaw@gmail.com>"]
edition.workspace = true

[[bin]]

name = "addressbook"
path = "addressbook.rs"

[dependencies]
capnp-import.workspace = true
capnp.workspace = true
