[package]

name = "hello-world"
version = "0.0.0"
authors = ["Mostafa Sedaghat Joo <mostafa.sedaghat@gmail.com>"]
edition = "2021"

[[bin]]
name = "hello-world"
path = "main.rs"

[dependencies]
capnp = { path = "../../../capnp" }
capnp-import = { path = "../../../capnp-import" }
futures = "0.3.0"
tokio = { version = "1.0.0", features = ["net", "rt", "macros"] }
tokio-util = { version = "0.7.4", features = ["compat"] }

[dependencies.capnp-rpc]
path = "../.."
