[package]

name = "hello-world"
version = "0.0.0"
authors = ["Mostafa Sedaghat Joo <mostafa.sedaghat@gmail.com>"]
edition.workspace = true

[[bin]]
name = "hello-world"
path = "main.rs"

[dependencies]
capnp.workspace = true
capnp-import.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
capnp-rpc.workspace = true
