[package]
name = "capnp-http-requests"
version = "0.1.0"
authors = ["David Renshaw <david@sandstorm.io>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "http-requests"
path = "src/main.rs"

[build-dependencies]
capnpc = { path = "../../../capnpc" }

[dependencies]
capnp = { path = "../../../capnp" }
futures = "0.3.0"
hyper = "0.13.1"
tokio = { version = "0.2.0", features = ["net", "rt-util", "tcp"]}
futures-tokio-compat = { git = "https://github.com/dwrensha/futures-tokio-compat", branch = "tokio-0.2" }

[dependencies.capnp-rpc]
path = "../.."
